---
spring:
  profiles: peer1                                 # 指定profile=peer1
server:
  port: 8761
eureka:
  instance:
    hostname: eureka-registry1                               # 指定当profile=eureka-registry1，主机名
  client:
    serviceUrl:
      defaultZone: http://peer2:8762/eureka/      # 将自己注册到eureka-registry2这个Eureka上面去

---
spring:
  profiles: peer2
server:
  port: 8762
eureka:
  instance:
    hostname: eureka-registry2
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/