node {
   def mvnHome
   def service_name
   def dockerComposeHome
   def dockerHome
   environment {
    EXE_DEV = "dev"
   }
   stage('获取源码') {
     // get source code from git* repo
      checkout([$class: 'GitSCM', branches: [[name: params.BRANCH]], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[url: 'https://github.com/dean-coding/micro-service-practice.git']]])
      // Get the Maven tool.
      // ** NOTE: This 'M3' Maven tool must be configured in the global configuration.
      mvnHome = '/usr/local/apache-maven-3.6.3'
      dockerComposeHome = '/usr/local'
      dockerHome = '/usr/bin'
      service_name = params.service_name
      echo "ready deploy project: ${service_name}"
   }
   stage('打包编译') {
     // Run the maven build
     sh "'${mvnHome}/bin/mvn' clean package -Dmaven.test.skip -pl ${service_name} -am"
   }
   stage('构建镜像') {
     sh "'${mvnHome}/bin/mvn' -pl ${service_name} -am dockerfile:build"
   }
   stage('构建容器') {
     sh "sh `pwd`/build-container.sh -s ${service_name}"
   }
}