version: '3.1'

services:
  ## 注册中心
  eureka-registry:
    image: eureka-registry:1.0.1
    container_name: eureka-registry
    #容器down掉后，会自动重启
#    restart: always
    #挂载一个目录,格式: 宿主机目录:容器内目录
    volumes:
      - /opt/data/logs:/logs
    environment:
      TZ: Asia/Shanghai
      MYSQL_HOST: hgdb
      MYSQL_DATABASE: prod
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8761:8761"
    networks:
      - dn-docker-net

  ## 网关服务
  gateway-service:
    image: gateway-service:1.0.1
    container_name: gateway-service
    volumes:
      - /opt/data/logs:/logs
    environment:
      TZ: Asia/Shanghai
      SPRING_PROFILES_ACTIVE: prod
      REGISTY_HOST: eureka-registry
    ports:
      - "9999:9999"
    depends_on:
      - eureka-registry
    links:
      - eureka-registry
    networks:
      - dn-docker-net

  ## 生产者资源服务
  producer-service:
    image: producer-service:1.0.1
    container_name: producer-service
    volumes:
      - /opt/data/logs:/logs
    environment:
      TZ: Asia/Shanghai
      SPRING_PROFILES_ACTIVE: prod
      REGISTY_HOST: eureka-registry
    ports:
      - "8881:8881"
    depends_on:
      - eureka-registry
    # [指定服务名称:别名] 将指定容器连接到当前连接，避免ip方式导致的容器重启动态改变的无法连接情况
    links:
      - eureka-registry
      - gateway-service
    networks:
      - dn-docker-net

  ## 消费者资源服务
  consumer-service:
    image: consumer-service:1.0.1
    container_name: consumer-service
    volumes:
      - /opt/data/logs:/logs
    environment:
      TZ: Asia/Shanghai
      SPRING_PROFILES_ACTIVE: prod
      REGISTY_HOST: eureka-registry
    ports:
      - "8882:8882"
    depends_on:
      - eureka-registry
    links:
      - eureka-registry
      - gateway-service
    networks:
      - dn-docker-net

networks:
  dn-docker-net:
      driver: bridge