server:
  port: 9999
spring:
  application:
    name: gateway-service
  cloud:
    ## 路由配置方式
    gateway:
      routes:
        - id: producer
          uri: lb://producer-service
          filters:
            - StripPrefix=1
            - name: Customer
              args:
                enabled: true
                excludePaths: /webjars/**,/swagger-ui.html/**,/swagger-ui/*,/swagger-resources/**,/v2/api-docs,/v3/api-docs
          predicates:
            - Path=/producer/**
        - id: consumer
          uri: lb://consumer-service
          filters:
            - StripPrefix=1
          predicates:
            - Path=/consumer/**
eureka:
  client:
    registry-fetch-interval-seconds: 5 # 客户端拉取服务注册信息间隔（缺省为30s） 对于api-gateway，如果要迅速获取服务注册状态，可以缩小该值，比如5秒。
    serviceUrl:
      defaultZone: http://${REGISTY_HOST:127.0.0.1}:8761/eureka/
  instance:
    hostname: gateway
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 5      # 心跳时间(client发送到server端)，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 15  # 发呆时间(server判断移除client的时长)，即服务续约到期时间（缺省为90s）

## 启用 {@link org.springframework.cloud.gateway.actuate.GatewayControllerEndpoint}
management:
  endpoints:
    web:
      exposure:
        # gateway,env
        include: "*"
auth:
  filter:
    excludePaths:
      - /consumer/**
      - /producer/**
logging:
  file: logs/${spring.application.name}/info.log