pipeline {
   def mvnHome
   environment {
    EXE_DEV = "dev"
   }
   stages {
      stage('获取源码') {
         // get source code from git* repo
         checkout([$class: 'GitSCM', branches: [[name: params.BRANCH]], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[url: 'https://github.com/dean-coding/micro-service-practice.git']]])
         // Get the Maven tool.
         // ** NOTE: This 'M3' Maven tool must be configured in the global configuration.
         mvnHome = '/usr/share/maven'
       }
      stage('打包编译') {
        // Run the maven build
        sh "'${mvnHome}/bin/mvn' clean package -Dmaven.test.skip -pl eureka-registry -am"
      }
      stage('构建镜像') {
        steps{
            sh "'${mvnHome}/bin/mvn' -pl eureka-registry -am dockerfile:build"
        }

     post {
            success {
            	 slackSend channel: '#ops-room',
                 color: 'good',
                 message: "The pipeline ${currentBuild.fullDisplayName} completed successfully."
            }
            unstable {
                echo 'I am unstable :/'
            }
            failure {
                echo 'I failed :('
            }
            changed {
                echo 'Things were different before...'
            }
       }
      }
      stage('测试') {
       echo "Hello Dean"
      }
   }
}